{% set name = "mlgb" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mlgb-{{ version }}.tar.gz
  sha256: 68b22a5663bcb908b0f02294508c77ae60c527b295b1a0b3b2aeb510a4c23fef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy >=1.23.0
    - pandas >=1.5.0
    - scikit-learn >=1.3.0
    - pytorch >=2.1.0
    - tensorflow >=2.10.0

test:
  imports:
    - mlgb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uliontse/mlgb
  summary: MLGB is a library that includes many models of CTR Prediction & Recommender System by TensorFlow & PyTorch.
  dev_url: https://github.com/UlionTse/mlgb
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - UlionTse
