{% set name = "mlgb" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mlgb-{{ version }}.tar.gz
  sha256: 100eaf695b492ca99ab1984baada98434d1b46a2461c247da3a6b5755e5e1e35

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.26.4
    - pandas >=1.5.3
    - scikit-learn >=1.6.1
    - pytorch >=2.1.0
    - tensorflow >=2.10.0

test:
  imports:
    - mlgb
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/uliontse/mlgb
  summary: MLGB is a library that includes many models of CTR Prediction & Recommender System by TensorFlow & PyTorch.
  dev_url: https://github.com/UlionTse/mlgb
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - UlionTse
